name: novel_reader
description: LN Reader App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  url_strategy: ^0.2.0
  get: ^4.3.8
  flutter_html: ^2.1.4
  http: ^0.13.4
  html: ^0.15.0
  getwidget: ^2.0.4
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.1.0
  simple_animations: ^4.0.1
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: false
  web: true
  windows: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
  - assets/
  - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
